version: '3.1'

services:

  db:
    image: postgres
    restart: always
    container_name: aws-postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: mysecretpassword
    ports:
      - "5432:5432"
